import { sql } from 'drizzle-orm';
import { check, index, integer, sqliteTable, text, uniqueIndex } from 'drizzle-orm/sqlite-core';

export const adminUsers = sqliteTable('admin_users', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  username: text('username').notNull().unique(),
  displayName: text('display_name').notNull(),
  passwordHash: text('password_hash').notNull(),
  status: text('status', { enum: ['active', 'disabled'] }).notNull().default('active'),
  lastLoginAt: text('last_login_at'),
  createdAt: text('created_at').notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text('updated_at').notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const adminSessions = sqliteTable(
  'admin_sessions',
  {
    sid: text('sid').primaryKey(),
    data: text('data').notNull(),
    expiresAt: integer('expires_at').notNull(),
    createdAt: text('created_at').notNull().default(sql`CURRENT_TIMESTAMP`),
    updatedAt: text('updated_at').notNull().default(sql`CURRENT_TIMESTAMP`),
  },
  (table) => [index('admin_sessions_expires_at_idx').on(table.expiresAt)],
);

export const states = sqliteTable(
  'states',
  {
    id: integer('id').primaryKey({ autoIncrement: true }),
    name: text('name').notNull(),
    code: text('code').notNull(),
    slug: text('slug').notNull(),
    country: text('country').notNull().default('United States'),
    anytimeUrl: text('anytime_url').notNull(),
    locationCount: integer('location_count').notNull().default(0),
    activeAddressCount: integer('active_address_count').notNull().default(0),
    residentialCount: integer('residential_count').notNull().default(0),
    lastCrawledAt: text('last_crawled_at'),
    createdAt: text('created_at').notNull().default(sql`CURRENT_TIMESTAMP`),
    updatedAt: text('updated_at').notNull().default(sql`CURRENT_TIMESTAMP`),
  },
  (table) => [
    uniqueIndex('states_code_unique').on(table.code),
    uniqueIndex('states_slug_unique').on(table.slug),
  ],
);

export const addresses = sqliteTable(
  'addresses',
  {
    id: integer('id').primaryKey({ autoIncrement: true }),
    source: text('source').notNull().default('anytimemailbox'),
    sourceId: text('source_id'),
    name: text('name').notNull(),
    slug: text('slug').notNull(),
    anytimeUrl: text('anytime_url').notNull(),
    signupUrl: text('signup_url'),
    googleMapsUrl: text('google_maps_url'),
    country: text('country').notNull().default('United States'),
    state: text('state').notNull(),
    stateName: text('state_name').notNull(),
    city: text('city').notNull(),
    streetAddress: text('street_address').notNull(),
    postalCode: text('postal_code').notNull(),
    fullAddress: text('full_address').notNull(),
    priceCents: integer('price_cents').notNull(),
    priceCurrency: text('price_currency').notNull().default('USD'),
    pricePeriod: text('price_period').notNull().default('month'),
    rdi: text('rdi', { enum: ['Residential', 'Commercial'] }).notNull(),
    cmra: text('cmra', { enum: ['Yes', 'No'] }).notNull(),
    smartyRaw: text('smarty_raw'),
    smartyCheckedAt: text('smarty_checked_at'),
    smartyMatchStatus: text('smarty_match_status', { enum: ['verified', 'uncertain'] }).notNull().default('verified'),
    smartyMatchMessage: text('smarty_match_message'),
    mailboxMin: integer('mailbox_min'),
    mailboxMax: integer('mailbox_max'),
    mailboxCount: integer('mailbox_count'),
    mailboxNumbersJson: text('mailbox_numbers_json'),
    isFeatured: integer('is_featured', { mode: 'boolean' }).notNull().default(false),
    isActive: integer('is_active', { mode: 'boolean' }).notNull().default(true),
    isVisible: integer('is_visible', { mode: 'boolean' }).notNull().default(true),
    statusNote: text('status_note'),
    lastCrawledAt: text('last_crawled_at'),
    firstSeenAt: text('first_seen_at').notNull().default(sql`CURRENT_TIMESTAMP`),
    removedAt: text('removed_at'),
    createdAt: text('created_at').notNull().default(sql`CURRENT_TIMESTAMP`),
    updatedAt: text('updated_at').notNull().default(sql`CURRENT_TIMESTAMP`),
  },
  (table) => [
    uniqueIndex('addresses_anytime_url_unique').on(table.anytimeUrl),
    index('addresses_slug_idx').on(table.slug),
    index('addresses_state_idx').on(table.state),
    index('addresses_city_idx').on(table.city),
    index('addresses_postal_code_idx').on(table.postalCode),
    index('addresses_rdi_idx').on(table.rdi),
    index('addresses_cmra_idx').on(table.cmra),
    index('addresses_featured_idx').on(table.isFeatured),
    index('addresses_active_idx').on(table.isActive),
    index('addresses_visible_idx').on(table.isVisible),
    index('addresses_price_cents_idx').on(table.priceCents),
    index('addresses_updated_at_idx').on(table.updatedAt),
    check('addresses_rdi_check', sql`${table.rdi} IN ('Residential', 'Commercial')`),
    check('addresses_cmra_check', sql`${table.cmra} IN ('Yes', 'No')`),
    check('addresses_smarty_match_status_check', sql`${table.smartyMatchStatus} IN ('verified', 'uncertain')`),
  ],
);

export const addressEvents = sqliteTable(
  'address_events',
  {
    id: integer('id').primaryKey({ autoIncrement: true }),
    addressId: integer('address_id').references(() => addresses.id, { onDelete: 'set null' }),
    eventType: text('event_type', {
      enum: [
        'added',
        'removed',
        'restored',
        'price_changed',
      ],
    }).notNull(),
    oldValue: text('old_value'),
    newValue: text('new_value'),
    message: text('message'),
    createdAt: text('created_at').notNull().default(sql`CURRENT_TIMESTAMP`),
  },
  (table) => [
    index('address_events_address_id_idx').on(table.addressId),
    index('address_events_event_type_idx').on(table.eventType),
    index('address_events_created_at_idx').on(table.createdAt),
  ],
);

export const addressImages = sqliteTable(
  'address_images',
  {
    id: integer('id').primaryKey({ autoIncrement: true }),
    addressId: integer('address_id').notNull().references(() => addresses.id, { onDelete: 'cascade' }),
    type: text('type').notNull().default('street_view'),
    fileName: text('file_name').notNull(),
    publicUrl: text('public_url').notNull(),
    originalFileName: text('original_file_name').notNull(),
    mimeType: text('mime_type').notNull(),
    sizeBytes: integer('size_bytes').notNull(),
    altText: text('alt_text'),
    isPrimary: integer('is_primary', { mode: 'boolean' }).notNull().default(true),
    createdAt: text('created_at').notNull().default(sql`CURRENT_TIMESTAMP`),
    updatedAt: text('updated_at').notNull().default(sql`CURRENT_TIMESTAMP`),
  },
  (table) => [
    index('address_images_address_id_idx').on(table.addressId),
    index('address_images_primary_idx').on(table.isPrimary),
  ],
);

export const crawlTasks = sqliteTable(
  'crawl_tasks',
  {
    id: integer('id').primaryKey({ autoIncrement: true }),
    batchCode: text('batch_code').notNull(),
    generatedAt: text('generated_at').notNull().default(sql`CURRENT_TIMESTAMP`),
    createdType: text('created_type', { enum: ['manual', 'system'] }).notNull(),
    status: text('status', {
      enum: ['running', 'pause_requested', 'paused', 'stop_requested', 'stopped', 'completed'],
    }).notNull().default('running'),
    note: text('note'),
    createdBy: text('created_by').notNull(),
    pendingCount: integer('pending_count').notNull().default(0),
    successCount: integer('success_count').notNull().default(0),
    failedCount: integer('failed_count').notNull().default(0),
    totalCount: integer('total_count').notNull().default(0),
    createdAt: text('created_at').notNull().default(sql`CURRENT_TIMESTAMP`),
    updatedAt: text('updated_at').notNull().default(sql`CURRENT_TIMESTAMP`),
  },
  (table) => [
    uniqueIndex('crawl_tasks_batch_code_unique').on(table.batchCode),
    index('crawl_tasks_generated_at_idx').on(table.generatedAt),
    index('crawl_tasks_created_type_idx').on(table.createdType),
    index('crawl_tasks_status_idx').on(table.status),
    check('crawl_tasks_created_type_check', sql`${table.createdType} IN ('manual', 'system')`),
    check('crawl_tasks_status_check', sql`${table.status} IN ('running', 'pause_requested', 'paused', 'stop_requested', 'stopped', 'completed')`),
  ],
);

export const crawlSubtasks = sqliteTable(
  'crawl_subtasks',
  {
    id: integer('id').primaryKey({ autoIncrement: true }),
    taskId: integer('task_id').notNull().references(() => crawlTasks.id, { onDelete: 'cascade' }),
    taskType: text('task_type', {
      enum: [
        'fetch_states',
        'fetch_names',
        'fetch_addresses',
        'fetch_mailbox_numbers',
        'sync_smarty',
      ],
    }).notNull(),
    executionStatus: text('execution_status', {
      enum: ['pending', 'running', 'paused', 'completed'],
    }).notNull().default('pending'),
    resultStatus: text('result_status', { enum: ['success', 'failed', 'stopped'] }),
    errorMessage: text('error_message'),
    createdAt: text('created_at').notNull().default(sql`CURRENT_TIMESTAMP`),
    updatedAt: text('updated_at').notNull().default(sql`CURRENT_TIMESTAMP`),
  },
  (table) => [
    index('crawl_subtasks_task_id_idx').on(table.taskId),
    index('crawl_subtasks_task_type_idx').on(table.taskType),
    index('crawl_subtasks_execution_status_idx').on(table.executionStatus),
    index('crawl_subtasks_result_status_idx').on(table.resultStatus),
    check('crawl_subtasks_task_type_check', sql`${table.taskType} IN ('fetch_states', 'fetch_names', 'fetch_addresses', 'fetch_mailbox_numbers', 'sync_smarty')`),
    check('crawl_subtasks_execution_status_check', sql`${table.executionStatus} IN ('pending', 'running', 'paused', 'completed')`),
    check('crawl_subtasks_result_status_check', sql`${table.resultStatus} IS NULL OR ${table.resultStatus} IN ('success', 'failed', 'stopped')`),
  ],
);

export const crawlDiscoveredAddresses = sqliteTable(
  'crawl_discovered_addresses',
  {
    id: integer('id').primaryKey({ autoIncrement: true }),
    taskId: integer('task_id').notNull().references(() => crawlTasks.id, { onDelete: 'cascade' }),
    source: text('source').notNull().default('anytimemailbox'),
    sourceId: text('source_id'),
    stateName: text('state_name').notNull(),
    state: text('state').notNull(),
    stateUrl: text('state_url').notNull(),
    stateLocationCount: integer('state_location_count'),
    name: text('name').notNull(),
    slug: text('slug').notNull(),
    anytimeUrl: text('anytime_url').notNull(),
    signupUrl: text('signup_url'),
    myearUrl: text('myear_url'),
    country: text('country').notNull().default('United States'),
    city: text('city').notNull(),
    streetAddress: text('street_address').notNull(),
    postalCode: text('postal_code').notNull(),
    fullAddress: text('full_address').notNull(),
    normalizedAddressKey: text('normalized_address_key').notNull(),
    priceCents: integer('price_cents').notNull(),
    priceCurrency: text('price_currency').notNull().default('USD'),
    pricePeriod: text('price_period').notNull().default('month'),
    mailboxMin: integer('mailbox_min'),
    mailboxMax: integer('mailbox_max'),
    mailboxCount: integer('mailbox_count'),
    mailboxNumbersJson: text('mailbox_numbers_json'),
    rdi: text('rdi', { enum: ['Residential', 'Commercial'] }),
    cmra: text('cmra', { enum: ['Yes', 'No'] }),
    smartyRaw: text('smarty_raw'),
    smartyCheckedAt: text('smarty_checked_at'),
    smartyMatchStatus: text('smarty_match_status', { enum: ['verified', 'uncertain'] }),
    smartyMatchMessage: text('smarty_match_message'),
    smartyError: text('smarty_error'),
    smartySourceAddressId: integer('smarty_source_address_id').references(() => addresses.id, { onDelete: 'set null' }),
    crawlStatus: text('crawl_status', {
      enum: [
        'discovered',
        'mailbox_fetched',
        'smarty_reused',
        'smarty_pending',
        'smarty_failed',
        'imported',
        'skipped',
      ],
    }).notNull().default('discovered'),
    errorMessage: text('error_message'),
    importedAddressId: integer('imported_address_id').references(() => addresses.id, { onDelete: 'set null' }),
    createdAt: text('created_at').notNull().default(sql`CURRENT_TIMESTAMP`),
    updatedAt: text('updated_at').notNull().default(sql`CURRENT_TIMESTAMP`),
  },
  (table) => [
    uniqueIndex('crawl_discovered_task_url_unique').on(table.taskId, table.anytimeUrl),
    index('crawl_discovered_task_id_idx').on(table.taskId),
    index('crawl_discovered_anytime_url_idx').on(table.anytimeUrl),
    index('crawl_discovered_normalized_key_idx').on(table.normalizedAddressKey),
    index('crawl_discovered_status_idx').on(table.crawlStatus),
    index('crawl_discovered_imported_address_idx').on(table.importedAddressId),
    check('crawl_discovered_rdi_check', sql`${table.rdi} IS NULL OR ${table.rdi} IN ('Residential', 'Commercial')`),
    check('crawl_discovered_cmra_check', sql`${table.cmra} IS NULL OR ${table.cmra} IN ('Yes', 'No')`),
    check('crawl_discovered_smarty_match_status_check', sql`${table.smartyMatchStatus} IS NULL OR ${table.smartyMatchStatus} IN ('verified', 'uncertain')`),
    check('crawl_discovered_status_check', sql`${table.crawlStatus} IN ('discovered', 'mailbox_fetched', 'smarty_reused', 'smarty_pending', 'smarty_failed', 'imported', 'skipped')`),
  ],
);

export const proxyLibrary = sqliteTable(
  'proxy_library',
  {
    id: integer('id').primaryKey({ autoIncrement: true }),
    url: text('url').notNull(),
    note: text('note'),
    isActive: integer('is_active', { mode: 'boolean' }).notNull().default(true),
    lastTestStatus: text('last_test_status', {
      enum: ['not_tested', 'success', 'failed'],
    }).notNull().default('not_tested'),
    lastTestMessage: text('last_test_message'),
    lastTestSampleAddress: text('last_test_sample_address'),
    lastTestedAt: text('last_tested_at'),
    createdAt: text('created_at').notNull().default(sql`CURRENT_TIMESTAMP`),
    updatedAt: text('updated_at').notNull().default(sql`CURRENT_TIMESTAMP`),
  },
  (table) => [
    uniqueIndex('proxy_library_url_unique').on(table.url),
    index('proxy_library_active_idx').on(table.isActive),
    index('proxy_library_test_status_idx').on(table.lastTestStatus),
    check('proxy_library_test_status_check', sql`${table.lastTestStatus} IN ('not_tested', 'success', 'failed')`),
  ],
);

export const smartyCredentials = sqliteTable(
  'smarty_credentials',
  {
    id: integer('id').primaryKey({ autoIncrement: true }),
    authId: text('auth_id').notNull(),
    authTokenEncrypted: text('auth_token_encrypted').notNull(),
    isActive: integer('is_active', { mode: 'boolean' }).notNull().default(true),
    lastStatus: text('last_status', {
      enum: ['not_tested', 'success', 'failed'],
    }).notNull().default('not_tested'),
    lastMessage: text('last_message'),
    lastCheckedAt: text('last_checked_at'),
    lastUsedAt: text('last_used_at'),
    createdAt: text('created_at').notNull().default(sql`CURRENT_TIMESTAMP`),
    updatedAt: text('updated_at').notNull().default(sql`CURRENT_TIMESTAMP`),
  },
  (table) => [
    uniqueIndex('smarty_credentials_auth_id_unique').on(table.authId),
    index('smarty_credentials_active_idx').on(table.isActive),
    index('smarty_credentials_status_idx').on(table.lastStatus),
    check('smarty_credentials_status_check', sql`${table.lastStatus} IN ('not_tested', 'success', 'failed')`),
  ],
);

export const systemSettings = sqliteTable(
  'system_settings',
  {
    id: integer('id').primaryKey(),
    smartyAuthId: text('smarty_auth_id').notNull().default(''),
    smartyAuthTokenEncrypted: text('smarty_auth_token_encrypted'),
    smartyConnectionStatus: text('smarty_connection_status', {
      enum: ['not_configured', 'connected', 'failed'],
    }).notNull().default('not_configured'),
    smartyConnectionMessage: text('smarty_connection_message'),
    smartyLastTestedAt: text('smarty_last_tested_at'),
    smartyRemainingCredits: integer('smarty_remaining_credits'),
    smartyMonthlyUsed: integer('smarty_monthly_used'),
    smartyCreditsUpdatedAt: text('smarty_credits_updated_at'),
    autoUpdateEnabled: integer('auto_update_enabled', { mode: 'boolean' }).notNull().default(true),
    updateFrequencyDays: integer('update_frequency_days').default(1),
    updateHour: integer('update_hour').notNull().default(8),
    updateMinute: integer('update_minute').notNull().default(30),
    headCode: text('head_code').notNull().default(''),
    createdAt: text('created_at').notNull().default(sql`CURRENT_TIMESTAMP`),
    updatedAt: text('updated_at').notNull().default(sql`CURRENT_TIMESTAMP`),
  },
  (table) => [
    check('system_settings_singleton_check', sql`${table.id} = 1`),
    check('system_settings_smarty_status_check', sql`${table.smartyConnectionStatus} IN ('not_configured', 'connected', 'failed')`),
    check('system_settings_frequency_check', sql`${table.updateFrequencyDays} IS NULL OR ${table.updateFrequencyDays} IN (1, 2, 3, 4, 5, 10)`),
    check('system_settings_hour_check', sql`${table.updateHour} BETWEEN 0 AND 23`),
    check('system_settings_minute_check', sql`${table.updateMinute} IN (0, 30)`),
  ],
);
